require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/daily_records", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # DailyRecord. As you add validations to DailyRecord, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      DailyRecord.create! valid_attributes
      get daily_records_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      daily_record = DailyRecord.create! valid_attributes
      get daily_record_url(daily_record)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_daily_record_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      daily_record = DailyRecord.create! valid_attributes
      get edit_daily_record_url(daily_record)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new DailyRecord" do
        expect {
          post daily_records_url, params: { daily_record: valid_attributes }
        }.to change(DailyRecord, :count).by(1)
      end

      it "redirects to the created daily_record" do
        post daily_records_url, params: { daily_record: valid_attributes }
        expect(response).to redirect_to(daily_record_url(DailyRecord.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new DailyRecord" do
        expect {
          post daily_records_url, params: { daily_record: invalid_attributes }
        }.to change(DailyRecord, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post daily_records_url, params: { daily_record: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested daily_record" do
        daily_record = DailyRecord.create! valid_attributes
        patch daily_record_url(daily_record), params: { daily_record: new_attributes }
        daily_record.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the daily_record" do
        daily_record = DailyRecord.create! valid_attributes
        patch daily_record_url(daily_record), params: { daily_record: new_attributes }
        daily_record.reload
        expect(response).to redirect_to(daily_record_url(daily_record))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        daily_record = DailyRecord.create! valid_attributes
        patch daily_record_url(daily_record), params: { daily_record: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested daily_record" do
      daily_record = DailyRecord.create! valid_attributes
      expect {
        delete daily_record_url(daily_record)
      }.to change(DailyRecord, :count).by(-1)
    end

    it "redirects to the daily_records list" do
      daily_record = DailyRecord.create! valid_attributes
      delete daily_record_url(daily_record)
      expect(response).to redirect_to(daily_records_url)
    end
  end
end
