require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/daily_records", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # DailyRecord. As you add validations to DailyRecord, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      DailyRecord.create! valid_attributes
      get daily_records_url
      expect(response).to be_successful
    end
  end

  describe "GET /index (月ごとの絞り込み)" do
    let!(:this_month_record) { create(:daily_record, date: Date.new(2026, 7, 15)) }
    let!(:prev_month_record) { create(:daily_record, date: Date.new(2026, 6, 15)) }
    let!(:next_month_record) { create(:daily_record, date: Date.new(2026, 8, 15)) }

    def full_date(date)
      date.strftime("%Y年%-m月%-d日")
    end

    it "monthパラメータなしの場合は当月の記録のみ表示する" do
      travel_to(Date.new(2026, 7, 1)) do
        get daily_records_url
        expect(response.body).to include(full_date(this_month_record.date))
        expect(response.body).not_to include(full_date(prev_month_record.date))
        expect(response.body).not_to include(full_date(next_month_record.date))
      end
    end

    it "monthパラメータを指定するとその月の記録のみ表示する" do
      get daily_records_url(month: "2026-06")
      expect(response.body).to include(full_date(prev_month_record.date))
      expect(response.body).not_to include(full_date(this_month_record.date))
    end

    it "前月・次月へのリンクを表示する" do
      get daily_records_url(month: "2026-07")
      expect(response.body).to include(daily_records_path(month: "2026-06"))
      expect(response.body).to include(daily_records_path(month: "2026-08"))
    end
  end

  describe "GET /show, GET /edit の「一覧に戻る」リンク" do
    let!(:record) { create(:daily_record, date: Date.new(2026, 6, 15)) }

    it "GET /show は記録の月を引き継いだ一覧リンクを表示する" do
      get daily_record_url(record)
      expect(response.body).to include(daily_records_path(month: "2026-06"))
    end

    it "GET /edit はキャンセルで詳細ページに戻るリンクを表示する" do
      get edit_daily_record_url(record)
      expect(response.body).to include(daily_record_path(record))
    end

    it "GET /new はキャンセルで一覧リンクを表示する" do
      get new_daily_record_url
      expect(response.body).to include(%(href="#{daily_records_path}"))
    end
  end

  describe "DELETE /destroy の月引き継ぎ" do
    let!(:record) { create(:daily_record, date: Date.new(2026, 6, 15)) }

    it "削除後、削除した記録の月の一覧にリダイレクトする" do
      delete daily_record_url(record)
      expect(response).to redirect_to(daily_records_url(month: "2026-06"))
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      daily_record = DailyRecord.create! valid_attributes
      get daily_record_url(daily_record)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_daily_record_url
      expect(response).to be_successful
    end

    it "前日の畜種を引き継ぐ" do
      livestock_type = create(:livestock_type)
      create(:daily_record, date: Date.current - 1, livestock_type: livestock_type)

      get new_daily_record_url

      expect(response.body).to include(%(selected="selected" value="#{livestock_type.id}"))
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      daily_record = DailyRecord.create! valid_attributes
      get edit_daily_record_url(daily_record)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new DailyRecord" do
        expect {
          post daily_records_url, params: { daily_record: valid_attributes }
        }.to change(DailyRecord, :count).by(1)
      end

      it "redirects to the created daily_record" do
        post daily_records_url, params: { daily_record: valid_attributes }
        expect(response).to redirect_to(daily_record_url(DailyRecord.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new DailyRecord" do
        expect {
          post daily_records_url, params: { daily_record: invalid_attributes }
        }.to change(DailyRecord, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post daily_records_url, params: { daily_record: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested daily_record" do
        daily_record = DailyRecord.create! valid_attributes
        patch daily_record_url(daily_record), params: { daily_record: new_attributes }
        daily_record.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the daily_record" do
        daily_record = DailyRecord.create! valid_attributes
        patch daily_record_url(daily_record), params: { daily_record: new_attributes }
        daily_record.reload
        expect(response).to redirect_to(daily_record_url(daily_record))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        daily_record = DailyRecord.create! valid_attributes
        patch daily_record_url(daily_record), params: { daily_record: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested daily_record" do
      daily_record = DailyRecord.create! valid_attributes
      expect {
        delete daily_record_url(daily_record)
      }.to change(DailyRecord, :count).by(-1)
    end

    it "redirects to the daily_records list" do
      daily_record = DailyRecord.create! valid_attributes
      delete daily_record_url(daily_record)
      expect(response).to redirect_to(daily_records_url)
    end
  end
end
