require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/daily_records", type: :request do
  let(:valid_attributes) do
    attributes_for(:daily_record).merge(head_count: 20)
  end

  let(:invalid_attributes) do
    { date: nil, death_count: nil, feed_usage: nil, feed_stock: nil }
  end

  describe "GET /index" do
    it "200を返す" do
      create(:daily_record)
      get daily_records_url
      expect(response).to have_http_status(:ok)
    end
  end

  describe "GET /index (月ごとの絞り込み)" do
    let!(:this_month_record) { create(:daily_record, date: Date.new(2026, 7, 15)) }
    let!(:prev_month_record) { create(:daily_record, date: Date.new(2026, 6, 15)) }
    let!(:next_month_record) { create(:daily_record, date: Date.new(2026, 8, 15)) }

    def full_date(date)
      date.strftime("%Y年%-m月%-d日")
    end

    it "monthパラメータなしの場合は当月の記録のみ表示する" do
      travel_to(Date.new(2026, 7, 1)) do
        get daily_records_url
        expect(response.body).to include(full_date(this_month_record.date))
        expect(response.body).not_to include(full_date(prev_month_record.date))
        expect(response.body).not_to include(full_date(next_month_record.date))
      end
    end

    it "monthパラメータを指定するとその月の記録のみ表示する" do
      get daily_records_url(month: "2026-06")
      expect(response.body).to include(full_date(prev_month_record.date))
      expect(response.body).not_to include(full_date(this_month_record.date))
    end

    it "前月・次月へのリンクを表示する" do
      get daily_records_url(month: "2026-07")
      expect(response.body).to include(daily_records_path(month: "2026-06"))
      expect(response.body).to include(daily_records_path(month: "2026-08"))
    end
  end

  describe "GET /show, GET /edit の「一覧に戻る」リンク" do
    let!(:record) { create(:daily_record, date: Date.new(2026, 6, 15)) }

    it "GET /show は記録の月を引き継いだ一覧リンクを表示する" do
      get daily_record_url(record)
      expect(response.body).to include(daily_records_path(month: "2026-06"))
    end

    it "GET /edit はキャンセルで詳細ページに戻るリンクを表示する" do
      get edit_daily_record_url(record)
      expect(response.body).to include(daily_record_path(record))
    end

    it "GET /new はキャンセルで一覧リンクを表示する" do
      get new_daily_record_url
      expect(response.body).to include(%(href="#{daily_records_path}"))
    end
  end

  describe "GET /show のワクチン接種記録への導線" do
    it "vaccineが「なし」のときは導線を表示しない" do
      record = create(:daily_record, date: Date.new(2026, 6, 18), vaccine: "なし")
      get daily_record_url(record)
      expect(response.body).not_to include("接種記録を追加")
      expect(response.body).not_to include("接種記録を見る")
    end

    it "vaccineが「なし」以外で該当するワクチン記録が無いときは新規作成への導線を表示する" do
      record = create(:daily_record, date: Date.new(2026, 6, 18), vaccine: "口蹄疫")
      get daily_record_url(record)
      expect(response.body).to include("接種記録を追加")
      expected_path = CGI.escapeHTML(new_vaccine_record_path(vaccinated_on: record.date, vaccine_name: record.vaccine))
      expect(response.body).to include(expected_path)
    end

    it "同じ日付のワクチン記録が既にあるときはその詳細への導線を表示する" do
      record = create(:daily_record, date: Date.new(2026, 6, 18), vaccine: "口蹄疫")
      vaccine_record = create(:vaccine_record, vaccinated_on: record.date)
      get daily_record_url(record)
      expect(response.body).to include("#{vaccine_record.vaccine_name}を見る")
      expect(response.body).to include(vaccine_record_path(vaccine_record))
    end

    it "同じ日付に複数のワクチン記録があるときはそれぞれへの導線を表示する" do
      record = create(:daily_record, date: Date.new(2026, 6, 18), vaccine: "口蹄疫")
      first_record = create(:vaccine_record, vaccinated_on: record.date, vaccine_name: "口蹄疫ワクチン")
      second_record = create(:vaccine_record, vaccinated_on: record.date, vaccine_name: "ブルセラワクチン")
      get daily_record_url(record)
      expect(response.body).to include("#{first_record.vaccine_name}を見る")
      expect(response.body).to include(vaccine_record_path(first_record))
      expect(response.body).to include("#{second_record.vaccine_name}を見る")
      expect(response.body).to include(vaccine_record_path(second_record))
    end
  end

  describe "DELETE /destroy の月引き継ぎ" do
    let!(:record) { create(:daily_record, date: Date.new(2026, 6, 15)) }

    it "削除後、削除した記録の月の一覧にリダイレクトする" do
      delete daily_record_url(record)
      expect(response).to redirect_to(daily_records_url(month: "2026-06"))
    end
  end

  describe "GET /show" do
    it "200を返す" do
      daily_record = create(:daily_record)
      get daily_record_url(daily_record)
      expect(response).to have_http_status(:ok)
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_daily_record_url
      expect(response).to be_successful
    end

    it "前日の畜種を引き継ぐ" do
      livestock_type = create(:livestock_type)
      create(:daily_record, date: Date.current - 1, livestock_type: livestock_type)

      get new_daily_record_url

      expect(response.body).to include(%(selected="selected" value="#{livestock_type.id}"))
    end
  end

  describe "GET /edit" do
    it "200を返す" do
      daily_record = create(:daily_record)
      get edit_daily_record_url(daily_record)
      expect(response).to have_http_status(:ok)
    end
  end

  describe "POST /create" do
    context "有効なパラメータのとき" do
      it "日次記録を1件作成する" do
        expect {
          post daily_records_url, params: { daily_record: valid_attributes }
        }.to change(DailyRecord, :count).by(1)
      end

      it "詳細ページにリダイレクトする" do
        post daily_records_url, params: { daily_record: valid_attributes }
        expect(response).to redirect_to(daily_record_url(DailyRecord.last))
      end
    end

    context "無効なパラメータのとき" do
      it "日次記録を作成しない" do
        expect {
          post daily_records_url, params: { daily_record: invalid_attributes }
        }.not_to change(DailyRecord, :count)
      end

      it "422を返す" do
        post daily_records_url, params: { daily_record: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "有効なパラメータのとき" do
      it "日次記録を更新して詳細ページにリダイレクトする" do
        daily_record = create(:daily_record)
        patch daily_record_url(daily_record), params: { daily_record: { feed_stock: 250 } }
        expect(response).to redirect_to(daily_record_url(daily_record))
        daily_record.reload
        expect(daily_record.feed_stock).to eq(250)
      end
    end

    context "無効なパラメータのとき" do
      it "422を返す" do
        daily_record = create(:daily_record)
        patch daily_record_url(daily_record), params: { daily_record: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "日次記録を削除して303を返す" do
      daily_record = create(:daily_record)
      expect {
        delete daily_record_url(daily_record)
      }.to change(DailyRecord, :count).by(-1)
      expect(response).to have_http_status(:see_other)
    end
  end
end
